### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by pjdurai** [KingMario/Max3#1]
Greetings

I am an ex MaxTo user who is exploring other options. I came across your very interesting project and think this will be perfect.

But I use a different configuration than yours ( 2 vertical monitors + one horizontal laptop screen) and I would like to customize the script to my setup.

Is it possible for you to add some explanation to your script so that I can get a good start? I can familiarize myself with AutoHotKey functions and it would help a lot if you could add some explanation to the source about your thoughts.

Appreciate your time.

Thanks
pj

**Comment by KingMario** [comment]
Added some explanation for the script. Hope it will help.

**Comment by pjdurai** [comment]
Thank you very much.
Thats exactly what I needed.

**Comment by KingMario** [comment]
@pjdurai any time.
